/**:
  ros__parameters:
    common:
      lidar_frame: "seyond"
      imu_frame: "vectornav"
      map_frame: "odom"
      base_frame: "vectornav"
      
    gravity_alignment:
      enable_gravity_alignment: false

    preprocess:
      lidar_type: 3               # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
      scan_line: 192
      scan_rate: 10               # only need to be set for velodyne, unit: Hz,
      timestamp_unit: 3           # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
      blind: 1.0
      blind_for_human_pilot: 1.0  # This parameter is to reject cloud points from human pilots

    mapping:
      acc_cov: 0.1
      gyr_cov: 0.1
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      fov_degree: 120.0
      det_range: 120.0
      extrinsic_est_en: false      # true: enable the online estimation of IMU-LiDAR extrinsic,

      # NOTE(hlim): In `vbr_calib.yaml`, it says:
      #imu:
      #  T_b:
      #  - [0.9994652045891429, 0.03194161690749185, -0.00698788259543323, -0.045630250613467524]
      #  - [-0.03200263570684775, 0.9994490166874298, -0.008798074077210848, -0.00784852988506693]
      #  - [0.006703021917434096, 0.009017052443448963, 0.9999368527795895, -0.6084150115067585]
      #  - [0.0, 0.0, 0.0, 1.0]
      # However, this matrix is tranformation of IMU w.r.t. LiDAR frame.
      # What we need is transformation LiDAR w.r.t. (or to) IMU frame; thus, the inverse matrix should be given
      extrinsic_T: [0.0, 0.0, 0.16]
      extrinsic_R: [1.0, 0.0, 0.0,
                    0.0, 1.0, 0.0,
                    0.0, 0.0, 1.0]

    filter_size_map: 1.0 #0.5

    topics:
      # Subscribers
      lidar: "/iv_points"
      imu: "/vectornav/imu"
      # Publishers
      cloud_registered: "fast_lio/cloud_registered"
      cloud_registered_lidar: "fast_lio/cloud_registered_lidar"
      cloud_registered_body: "fast_lio/cloud_registered_body"
      cloud_registered_base: "fast_lio/cloud_registered_base"
      cloud_map: "fast_lio/cloud_map"
      odometry: "fast_lio/odometry"
      path: "fast_lio/path"

    publish:
      path_en: true
      scan_publish_en: true        # false: close all the point cloud output
      dense_publish_en: false       # false: low down the points number in a global-frame point clouds scan.
      scan_lidarframe_pub_en: true # true: output the point cloud scans in the LiDAR frame
      scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body frame
      scan_baseframe_pub_en: false  # true: output the point cloud scans in the base frame
      map_pub_interval: 10          # publish map every N scans (0 to disable)

    pcd_save:
      pcd_save_en: false
      save_path: ""                # directory to save scans and poses (empty = <package>/PCD)
      interval: 1                 # how many LiDAR frames saved in each pcd file;
      # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

    verbose: true
    pcl_verbose: false
    runtime_pos_log_enable: true
    point_filter_num_for_preprocessing: 1 # If it is set to `1`, full point cloud gonna be publlished
    point_filter_num: 2                   # For pose estimation.
    max_iteration: 4
    cube_side_length: 1000.0
